services:
  web:
    build: .
    image: test-express-server:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src:/app/src  # Optional, for local development
